PACKAGE_NAME="planeradar-hyperpixel2r"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="planeradar_hyperpixel2r"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
CLEAN="make clean"
MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=/lib/modules/${kernelver}/build modules"
